[package]
name = "win-audio-sessions"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/yggdrion/win-audio-sessions"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi9"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
